name: CI Test Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #　リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      #　Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      #　依存関係のインストール
      - name: Install dependencies
        run: npm ci

      #　Storybookをビルド
      - name: Build Storybook
        run: npm run build-storybook
